#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
DEPLOY_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd)
SOURCE_ROOT=${SOURCE_ROOT:-$(cd -- "$DEPLOY_DIR/.." && pwd)}
FRONTEND_MODULES_CONFIG=${FRONTEND_MODULES_CONFIG:-$DEPLOY_DIR/frontend-modules.json}
TARGET_FILE=${TARGET_FILE:-$SOURCE_ROOT/webui/src/dashboard/generated-module-registry.ts}
DECLARATION_FILE=${DECLARATION_FILE:-$SOURCE_ROOT/webui/src/dashboard/remote-modules.d.ts}

if [[ ! -f "$FRONTEND_MODULES_CONFIG" ]]; then
  printf '[sync-dashboard-modules] frontend module config not found: %s\n' "$FRONTEND_MODULES_CONFIG" >&2
  exit 1
fi

python3 - "$FRONTEND_MODULES_CONFIG" "$TARGET_FILE" "$DECLARATION_FILE" <<'PY'
import json
import os
import re
import sys

config_path, target_file, declaration_file = sys.argv[1:4]

with open(config_path, "r", encoding="utf-8") as handle:
    modules = (json.load(handle).get("modules") or [])

if not modules:
    raise SystemExit(f"frontend module config has no modules: {config_path}")

seen_remotes: set[str] = set()
imports: list[dict[str, str]] = []
section_names = {
    "main": "DASHBOARD_NAV_SECTION_MAIN",
    "infrastructure": "DASHBOARD_NAV_SECTION_INFRASTRUCTURE",
    "lab": "DASHBOARD_NAV_SECTION_LAB",
}

for index, module in enumerate(modules):
    if module.get("enabled") is False:
        continue
    module_id = str(module.get("id") or module.get("name") or "").strip()
    remote_name = str(module.get("remoteName") or module.get("target") or module_id).strip()
    remote_entry = str(module.get("remoteEntry") or "").strip()
    exposed = str(module.get("exposedModule") or "./dashboardModule").strip()
    if not module_id or not remote_name or not remote_entry or not exposed:
        raise SystemExit(f"invalid frontend module entry in {config_path}: {module!r}")
    if remote_name in {".", ".."} or "/" in remote_name or "\\" in remote_name or remote_name in seen_remotes:
        raise SystemExit(f"invalid or duplicate frontend module remoteName: {remote_name}")
    if not exposed.startswith("./"):
        raise SystemExit(f"invalid exposedModule for {module_id}: {exposed}")
    nav_key = str(module.get("navKey") or module_id).strip()
    nav_label = str(module.get("navLabel") or module.get("name") or module_id).strip()
    nav_icon = str(module.get("navIcon") or module_id).strip()
    nav_section = str(module.get("navSection") or "main").strip().lower()
    nav_order = int(module.get("navOrder") or index)
    required_services = module.get("requiredServices") or ([module.get("service")] if module.get("service") else [])
    if nav_section not in section_names:
        raise SystemExit(f"invalid navSection for {module_id}: {nav_section}")
    seen_remotes.add(remote_name)
    specifier = f"{remote_name}/{exposed[2:]}"
    safe = re.sub(r"[^0-9A-Za-z_$]", "_", remote_name)
    if not safe or safe[0].isdigit():
        safe = f"module_{index}"
    imports.append({
        "id": module_id,
        "remote": remote_name,
        "remote_entry": remote_entry,
        "specifier": specifier,
        "variable": f"load_{safe}",
        "nav_key": nav_key,
        "nav_label": nav_label,
        "nav_icon": nav_icon,
        "nav_section": section_names[nav_section],
        "nav_order": nav_order,
        "required_services": [str(value).strip() for value in required_services if str(value).strip()],
    })

os.makedirs(os.path.dirname(target_file), exist_ok=True)
with open(target_file, "w", encoding="utf-8") as output:
    output.write("// Code generated by deploy/scripts/sync-dashboard-modules.sh; DO NOT EDIT.\n")
    output.write("import { loadRemote, registerRemotes } from '@module-federation/runtime';\n")
    output.write("import { createElement, lazy, Suspense } from 'react';\n")
    output.write("import { DashboardNavSection, type DashboardModuleRegistration, type DashboardModuleViewProps } from './module-contract';\n\n")
    output.write("type RemoteDashboardModule = { default?: DashboardModuleRegistration } | DashboardModuleRegistration | null;\n")
    output.write("type LazyView = (props: DashboardModuleViewProps) => ReturnType<typeof createElement>;\n\n")
    output.write("const moduleRegistrations: DashboardModuleRegistration[] = [\n")
    for item in imports:
        output.write("  {\n")
        output.write(f"    manifest: {{ id: {item['id']!r}, nav: [{{ key: {item['nav_key']!r}, label: {item['nav_label']!r}, icon: {item['nav_icon']!r}, section: DashboardNavSection.{item['nav_section']}, required_services: {item['required_services']!r}, order: {item['nav_order']} }}] }},\n")
        output.write(f"    views: {{ {item['nav_key']!r}: lazyDashboardView({item['id']!r}, {item['remote']!r}, {item['remote_entry']!r}, {item['specifier']!r}, {item['nav_key']!r}) }}\n")
        output.write("  },\n")
    output.write("];\n\n")
    output.write("export async function loadDashboardModuleRegistrations(): Promise<DashboardModuleRegistration[]> {\n")
    output.write("  return [...moduleRegistrations].sort((left, right) => left.manifest.id.localeCompare(right.manifest.id));\n")
    output.write("}\n\n")
    output.write("function lazyDashboardView(id: string, remoteName: string, remoteEntry: string, specifier: string, viewKey: string): LazyView {\n")
    output.write("  const Component = lazy(async () => {\n")
    output.write("    try {\n")
    output.write("      registerRemotes([{ name: remoteName, entry: remoteEntry, type: 'module' }]);\n")
    output.write("      const registration = normalizeRegistration(await loadRemote<RemoteDashboardModule>(specifier));\n")
    output.write("      const View = registration?.views?.[viewKey];\n")
    output.write("      return { default: View || (() => createElement(RemoteModuleError, { id, message: `view ${viewKey} is not registered` })) };\n")
    output.write("    } catch (error) {\n")
    output.write("      const message = error instanceof Error ? error.message : String(error);\n")
    output.write("      return { default: () => createElement(RemoteModuleError, { id, message }) };\n")
    output.write("    }\n")
    output.write("  });\n")
    output.write("  return (props) => createElement(Suspense, { fallback: createElement(RemoteModuleLoading, { id }) }, createElement(Component as any, props));\n")
    output.write("}\n\n")
    output.write("function normalizeRegistration(module: RemoteDashboardModule): DashboardModuleRegistration | null {\n")
    output.write("  if (!module) return null;\n")
    output.write("  if ('manifest' in module) return module;\n")
    output.write("  return module.default || null;\n")
    output.write("}\n")
    output.write("\nfunction RemoteModuleLoading({ id }: { id: string }) {\n")
    output.write("  return createElement('div', { className: 'p-6 text-sm text-muted-foreground' }, `正在加载 ${id} 模块…`);\n")
    output.write("}\n")
    output.write("\nfunction RemoteModuleError({ id, message }: { id: string; message: string }) {\n")
    output.write("  return createElement('div', { className: 'p-6 text-sm text-destructive' }, `${id} 模块加载失败：${message}`);\n")
    output.write("}\n")

os.makedirs(os.path.dirname(declaration_file), exist_ok=True)
with open(declaration_file, "w", encoding="utf-8") as output:
    output.write("// Code generated by deploy/scripts/sync-dashboard-modules.sh; DO NOT EDIT.\n")
    output.write("type DashboardRemoteRegistration = import('./module-contract').DashboardModuleRegistration;\n\n")
    for item in imports:
        output.write(f"declare module {item['specifier']!r} {{\n")
        output.write("  const registration: DashboardRemoteRegistration;\n")
        output.write("  export default registration;\n")
        output.write("}\n\n")

print(f"[sync-dashboard-modules] generated {target_file} and {declaration_file} from {config_path}")
PY
