#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
DEPLOY_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd)
SOURCE_ROOT=${SOURCE_ROOT:-$(cd -- "$DEPLOY_DIR/.." && pwd)}
FRONTEND_MODULES_CONFIG=${FRONTEND_MODULES_CONFIG:-$DEPLOY_DIR/frontend-modules.json}
TARGET_FILE=${TARGET_FILE:-$SOURCE_ROOT/webui/src/dashboard/generated-module-registry.ts}
DECLARATION_FILE=${DECLARATION_FILE:-$SOURCE_ROOT/webui/src/dashboard/remote-modules.d.ts}

if [[ ! -f "$FRONTEND_MODULES_CONFIG" ]]; then
  printf '[sync-dashboard-modules] frontend module config not found: %s\n' "$FRONTEND_MODULES_CONFIG" >&2
  exit 1
fi

python3 - "$FRONTEND_MODULES_CONFIG" "$TARGET_FILE" "$DECLARATION_FILE" <<'PY'
import json
import os
import re
import sys

config_path, target_file, declaration_file = sys.argv[1:4]

with open(config_path, "r", encoding="utf-8") as handle:
    modules = (json.load(handle).get("modules") or [])

if not modules:
    raise SystemExit(f"frontend module config has no modules: {config_path}")

seen_remotes: set[str] = set()
imports: list[dict[str, str]] = []

for index, module in enumerate(modules):
    if module.get("enabled") is False:
        continue
    module_id = str(module.get("id") or module.get("name") or "").strip()
    remote_name = str(module.get("remoteName") or module.get("target") or module_id).strip()
    exposed = str(module.get("exposedModule") or "./dashboardModule").strip()
    if not module_id or not remote_name or not exposed:
        raise SystemExit(f"invalid frontend module entry in {config_path}: {module!r}")
    if remote_name in {".", ".."} or "/" in remote_name or "\\" in remote_name or remote_name in seen_remotes:
        raise SystemExit(f"invalid or duplicate frontend module remoteName: {remote_name}")
    if not exposed.startswith("./"):
        raise SystemExit(f"invalid exposedModule for {module_id}: {exposed}")
    seen_remotes.add(remote_name)
    specifier = f"{remote_name}/{exposed[2:]}"
    safe = re.sub(r"[^0-9A-Za-z_$]", "_", remote_name)
    if not safe or safe[0].isdigit():
        safe = f"module_{index}"
    imports.append({"id": module_id, "remote": remote_name, "specifier": specifier, "variable": f"load_{safe}"})

os.makedirs(os.path.dirname(target_file), exist_ok=True)
with open(target_file, "w", encoding="utf-8") as output:
    output.write("// Code generated by deploy/scripts/sync-dashboard-modules.sh; DO NOT EDIT.\n")
    output.write("import type { DashboardModuleRegistration } from './module-contract';\n\n")
    output.write("type RemoteDashboardModule = { default?: DashboardModuleRegistration };\n")
    output.write("type DashboardModuleLoader = () => Promise<RemoteDashboardModule>;\n\n")
    output.write("const moduleLoaders: Array<{ id: string; load: DashboardModuleLoader }> = [\n")
    for item in imports:
        output.write(f"  {{ id: {item['id']!r}, load: () => import({item['specifier']!r}) }},\n")
    output.write("];\n\n")
    output.write("export async function loadDashboardModuleRegistrations(): Promise<DashboardModuleRegistration[]> {\n")
    output.write("  const modules = await Promise.all(\n")
    output.write("    moduleLoaders.map(async ({ id, load }) => {\n")
    output.write("      try {\n")
    output.write("        return (await load()).default || null;\n")
    output.write("      } catch (error) {\n")
    output.write("        console.error(`failed to load dashboard module ${id}`, error);\n")
    output.write("        return null;\n")
    output.write("      }\n")
    output.write("    })\n")
    output.write("  );\n")
    output.write("  return modules\n")
    output.write("    .filter((registration): registration is DashboardModuleRegistration => !!registration?.manifest?.id)\n")
    output.write("    .sort((left, right) => left.manifest.id.localeCompare(right.manifest.id));\n")
    output.write("}\n")

os.makedirs(os.path.dirname(declaration_file), exist_ok=True)
with open(declaration_file, "w", encoding="utf-8") as output:
    output.write("// Code generated by deploy/scripts/sync-dashboard-modules.sh; DO NOT EDIT.\n")
    output.write("type DashboardRemoteRegistration = import('./module-contract').DashboardModuleRegistration;\n\n")
    for item in imports:
        output.write(f"declare module {item['specifier']!r} {{\n")
        output.write("  const registration: DashboardRemoteRegistration;\n")
        output.write("  export default registration;\n")
        output.write("}\n\n")

print(f"[sync-dashboard-modules] generated {target_file} and {declaration_file} from {config_path}")
PY
